### ISSUE TITLE
playdoh command line tool should not require wx

### ISSUE THREAD

**Issue by astrofrog** [rossant/playdoh#1]
When running e.g. `playdoh open` or `playdoh close <server>` or other commands not requiring a GUI, it would be great if wxPython wasn't required since it's not used. Even though I don't need a GUI, I spent a while installing wxPython from source on a server, just so as to be able to use the command-line tool. Would it be possible to make it so that wxPython is only required if actually launching the GUI?

**Comment by rossant** [comment]
Thanks for that, it should be fixed now!

**Comment by astrofrog** [comment]
Thanks for the quick fix!
